namespace Ernaehrbar.Adapters.Infrastructure.Data.Entities;

/// <summary>
/// Source/Origin of a recipe.
/// </summary>
public enum RecipeSource
{
    /// <summary>
    /// Generated by AI/LLM.
    /// </summary>
    Generated = 1,

    /// <summary>
    /// Uploaded from PDF/image.
    /// </summary>
    Upload = 2,

    /// <summary>
    /// Manually created by user.
    /// </summary>
    Manual = 3
}
